### ISSUE TITLE
Rethink about the storage model that works well with emerging APIs (SW, storage durability API etc)

### ISSUE THREAD

**Issue by kinu** [kinu/quota-api#13]
`persistent` storage concept is only integrated into http://www.w3.org/TR/file-system-api/ (which is now dead), and all other storage APIs (e.g. IDB, Cache etc) do not have ability to express its storage's durability.  On the other hand several other proposals, like [Storage Pressure Events in ServiceWorker](http://kinu.github.io/quota-api/#storage-pressure-events) and [Storage Durability API] (https://github.com/slightlyoff/StorageDurability/blob/master/explainer.md) are emerging to handle app's data durability in a more flexible or straightforward way.  Perhaps it's time to rethink about the `temporary` and `persistent` concept and simplify / clarify a typical eviction scenario, there can be just one 'web storage' that can be maintained via Storage Pressure Events and be upgraded to persistent one via Storage Durability API?

**Comment by domenic** [comment]
+1

**Comment by kinu** [comment]
https://github.com/w3c/quota-api/issues/2
