### ISSUE TITLE
How UA should manage per-scope storage for ServiceWorkers?

### ISSUE THREAD

**Issue by kinu** [kinu/quota-api#9]
For onbeforeevict events UA needs to tell how much space each ServiceWorker should free up, but ServiceWorkers are registered per scope while UA's logical application unit for storage management may be different (e.g. Chrome's logical unit for storage management is per-origin).

/cc @inexorabletash

**Comment by wanderview** [comment]
Since the storage is per-origin, it seems to me the events should be dispatched to all ServiceWorkers registered for the same origin.

**Comment by kinu** [comment]
Yeah I agree that that'd be the most reasonable approach. If we want to give some hints about how much more space is requested (i.e. `spaceRequested`) there's another question about whether all apps in the same origin should get the same number... if those scopes are a group of cooperative apps that'd be fine, but otherwise it could be a little awkward.

**Comment by wanderview** [comment]
The problem is the scope thing makes it seem like you can have "separate apps", but its kind of not true.  Each of these "apps" will share permissions and storage with each other.  They are certainly not isolated from each other as people would not expect with apps.

Of course this is more of a problem with the SW spec than the quota API.

**Comment by kinu** [comment]
That's true, scopes are just a unit of background operation but not a unit of app.  I suppose this means that all ServiceWorkers registered for the same origin should get same events (and if the event includes some info about usage/quota the info should be also shared too). I'm going to clarify that in the spec.

**Comment by kinu** [comment]
I think storage should just continue to be managed per-origin, and we should just remove any notion that gives the impression that the storage is managed per-scope etc. (Related: #14)
